### ISSUE TITLE
Docker group does not exist (yet)

### ISSUE THREAD

**Issue by seblegall** [csanquer/install-scripts#1]
When running the install script for the first time, there is an error because ansible try to add the current user  to the docker group before installing docker. So, the docker group does not exist yet...

**Comment by csanquer** [comment]
Ok I see two solutions :

1. use docker role before account role
2. or use the variable account_groups to create docker group before

```yml
account_groups: 
  docker:
    gid: 999
    system: true
```
